# Generated by Django 5.1 on 2024-08-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='reEnter',
        ),
        migrations.AlterField(
            model_name='signup',
            name='adharNumber',
            field=models.BigIntegerField(),
        ),
    ]
