# Generated by Django 5.1 on 2024-08-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0003_remove_signup_reenter_alter_signup_adharnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
