# Generated by Django 4.2.15 on 2024-08-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0004_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='adharNumber',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phoneNumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
