# Generated by Django 4.2.15 on 2024-08-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0005_alter_signup_adharnumber_alter_signup_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('numberOfWorker', models.IntegerField()),
                ('salaryPerDay', models.IntegerField()),
                ('jobDescription', models.TextField(null=True)),
            ],
        ),
    ]
