# Generated by Django 4.2.15 on 2024-08-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0006_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('jobDescription', models.TextField(null=True)),
                ('place', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default='2024-08-20')),
                ('timeSpan', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numberOfWorker', models.IntegerField()),
                ('salaryPerDay', models.IntegerField()),
                ('machineAvailable', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
