# Generated by Django 4.2.15 on 2024-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0007_job_workerhead_delete_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phoneNumber',
            field=models.BigIntegerField(default=1234567890),
        ),
    ]
