# Generated by Django 4.2.15 on 2024-08-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerhead',
            name='phoneNumber',
            field=models.BigIntegerField(default=1234567890),
        ),
    ]
