# Generated by Django 4.2.15 on 2024-08-21 02:19

from django.db import migrations, models


def populate_users(apps, schema_editor):
    Signup = apps.get_model('R_E', 'Signup')
    User = apps.get_model('auth', 'User')

    for signup in Signup.objects.all():
        user, created = User.objects.get_or_create(username=signup.phoneNumber, defaults={
            'password': 'defaultpassword'  # Set a default password or handle as needed
        })
        signup.user = user
        signup.save()


class Migration(migrations.Migration):
    dependencies = [
        ('R_E', '0012_job_user_workerhead_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(
                to='auth.user',
                on_delete=models.CASCADE,
                related_name='signup',
                null=True,  # Temporarily allow nulls to handle existing data
            ),
        ),
        migrations.RunPython(populate_users),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(
                to='auth.user',
                on_delete=models.CASCADE,
                related_name='signup',
                null=False,  # Ensure non-nullability after migration
            ),
        ),
    ]
