# Generated by Django 4.2.15 on 2024-08-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_users(apps, schema_editor):
    Signup = apps.get_model('R_E', 'Signup')
    User = apps.get_model('auth', 'User')

    for signup in Signup.objects.all():
        user, created = User.objects.get_or_create(username=signup.phoneNumber, defaults={
            'password': 'defaultpassword'  # Set a default password or handle as needed
        })
        signup.user = user
        signup.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('R_E', '0013_auto_20240821_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='signup',
                null=True,  # Temporarily allow nulls to handle existing data
            ),
        ),
        migrations.RunPython(populate_users),  # This will populate the 'user' field with existing users
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='signup',
                null=False,  # Ensure non-nullability after migration
            ),
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',  # Remove the password field as it's no longer needed
        ),
    ]
