# Generated by Django 4.2.15 on 2024-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0015_alter_signup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerhead',
            name='machineChargePerDay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerhead',
            name='machineImage',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images/'),
        ),
    ]
