# Generated by Django 4.2.15 on 2024-08-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0016_workerhead_machinechargeperday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerhead',
            old_name='machineChargePerDay',
            new_name='chargePerDay',
        ),
    ]
