# Generated by Django 4.2.15 on 2024-08-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0017_rename_machinechargeperday_workerhead_chargeperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerhead',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workerhead',
            name='machineImage',
            field=models.ImageField(blank=True, null=True, upload_to='machines/'),
        ),
    ]
