# Generated by Django 4.2.15 on 2024-09-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0019_workerhead_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='price',
            new_name='days',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
