# Generated by Django 4.2.15 on 2024-09-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0020_rename_price_job_days_alter_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='timeSpan',
        ),
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
