# Generated by Django 4.2.15 on 2024-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0021_remove_job_timespan_job_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timeSpan',
            field=models.TimeField(default='9:00'),
            preserve_default=False,
        ),
    ]
