# Generated by Django 4.2.15 on 2024-09-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0022_job_timespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.IntegerField(),
        ),
    ]
