# Generated by Django 4.2.15 on 2024-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0023_alter_job_days_alter_job_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phoneNumber',
            field=models.BigIntegerField(default=None),
        ),
    ]
