# Generated by Django 4.2.15 on 2024-09-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0026_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='Select'),
        ),
    ]
