# Generated by Django 4.2.15 on 2024-10-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0027_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
