# Generated by Django 4.2.15 on 2024-10-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0028_job_work_done_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='adharNumber',
            field=models.CharField(max_length=12),
        ),
    ]
