# Generated by Django 4.2.15 on 2024-11-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R_E', '0029_alter_signup_adharnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='R_E.workerhead'),
            preserve_default=False,
        ),
    ]
